<?php

/**
 * WacMaterialPurchaseOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialPurchaseOrderItemTable extends PluginWacMaterialPurchaseOrderItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialPurchaseOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialPurchaseOrderItem');
    }
}