<?php

/**
 * WacMaterialSalesOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialSalesOrderStateHistoryTable extends PluginWacMaterialSalesOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialSalesOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialSalesOrderStateHistory');
    }
}