<?php

/**
 * WacMaterialShippingOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialShippingOrderItemTable extends PluginWacMaterialShippingOrderItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialShippingOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialShippingOrderItem');
    }
}