<?php

/**
 * WacMaterialPurchaseOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialPurchaseOrderStateHistoryTable extends PluginWacMaterialPurchaseOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialPurchaseOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialPurchaseOrderStateHistory');
    }
}