<?php

/**
 * WacMaterialSaleOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialSaleOrderItemTable extends PluginWacMaterialSaleOrderItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialSaleOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialSaleOrderItem');
    }
}