<?php

/**
 * WacMaterialPurchaseOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialPurchaseOrderStateTable extends PluginWacMaterialPurchaseOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialPurchaseOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialPurchaseOrderState');
    }
}