<?php

/**
 * WacMaterialSalesOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialSalesOrderStateTable extends PluginWacMaterialSalesOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialSalesOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialSalesOrderState');
    }
}