<?php

/**
 * WacMaterialDeliveryOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialDeliveryOrderTable extends PluginWacMaterialDeliveryOrderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialDeliveryOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialDeliveryOrder');
    }
}