<?php

/**
 * WacMaterialCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialCategoryTable extends PluginWacMaterialCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialCategory');
    }
}