<?php

/**
 * WacMaterialDeliveryOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialDeliveryOrderStateTable extends PluginWacMaterialDeliveryOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialDeliveryOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialDeliveryOrderState');
    }
}