<?php

/**
 * WacMaterialSalesOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialSalesOrderItemTable extends PluginWacMaterialSalesOrderItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialSalesOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialSalesOrderItem');
    }
}