<?php

/**
 * WacOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacOrderStateTable extends PluginWacOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacOrderState');
    }
}