<?php

/**
 * WacStorehouseMaterialQuantityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacStorehouseMaterialQuantityTable extends PluginWacStorehouseMaterialQuantityTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacStorehouseMaterialQuantityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacStorehouseMaterialQuantity');
    }
}