<?php

/**
 * WacFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacFileTable extends PluginWacFileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacFile');
    }
}