<?php

/**
 * WacGuardPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacGuardPermissionTable extends PluginWacGuardPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacGuardPermission');
    }
}