<?php

/**
 * WacLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacLanguageTable extends PluginWacLanguageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacLanguage');
    }
}