<?php

/**
 * WacUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacUserTable extends PluginWacUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacUser');
    }
}