<?php

/**
 * PluginWacCurrencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacCurrencyTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacCurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacCurrency');
    }
}