<?php

/**
 * PluginWacUnitRatioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacUnitRatioTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacUnitRatioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacUnitRatio');
    }
}