<?php

/**
 * PluginWacTemplateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacTemplateTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacTemplateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacTemplate');
    }
}