<?php

/**
 * BaseWacGuardPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    WacERP
 * @subpackage model
 * @author     JianBinBi <jianbinbi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWacGuardPermission extends sfGuardPermission
{
    public function setUp()
    {
        parent::setUp();
        
    }
}