<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WacCurrencyRatio', 'wac_db_connection1');

/**
 * BaseWacCurrencyRatio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $ratio
 * @property integer $pr_int1
 * @property integer $pr_int2
 * @property integer $priority
 * @property integer $is_avail
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property string $from_currency_code
 * @property string $to_currency_code
 * @property string $pr_str1
 * @property string $pr_str2
 * @property WacCurrency $FromCurrency
 * @property WacCurrency $ToCurrency
 * 
 * @method integer          getId()                 Returns the current record's "id" value
 * @method float            getRatio()              Returns the current record's "ratio" value
 * @method integer          getPrInt1()             Returns the current record's "pr_int1" value
 * @method integer          getPrInt2()             Returns the current record's "pr_int2" value
 * @method integer          getPriority()           Returns the current record's "priority" value
 * @method integer          getIsAvail()            Returns the current record's "is_avail" value
 * @method timestamp        getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp        getUpdatedAt()          Returns the current record's "updated_at" value
 * @method string           getFromCurrencyCode()   Returns the current record's "from_currency_code" value
 * @method string           getToCurrencyCode()     Returns the current record's "to_currency_code" value
 * @method string           getPrStr1()             Returns the current record's "pr_str1" value
 * @method string           getPrStr2()             Returns the current record's "pr_str2" value
 * @method WacCurrency      getFromCurrency()       Returns the current record's "FromCurrency" value
 * @method WacCurrency      getToCurrency()         Returns the current record's "ToCurrency" value
 * @method WacCurrencyRatio setId()                 Sets the current record's "id" value
 * @method WacCurrencyRatio setRatio()              Sets the current record's "ratio" value
 * @method WacCurrencyRatio setPrInt1()             Sets the current record's "pr_int1" value
 * @method WacCurrencyRatio setPrInt2()             Sets the current record's "pr_int2" value
 * @method WacCurrencyRatio setPriority()           Sets the current record's "priority" value
 * @method WacCurrencyRatio setIsAvail()            Sets the current record's "is_avail" value
 * @method WacCurrencyRatio setCreatedAt()          Sets the current record's "created_at" value
 * @method WacCurrencyRatio setUpdatedAt()          Sets the current record's "updated_at" value
 * @method WacCurrencyRatio setFromCurrencyCode()   Sets the current record's "from_currency_code" value
 * @method WacCurrencyRatio setToCurrencyCode()     Sets the current record's "to_currency_code" value
 * @method WacCurrencyRatio setPrStr1()             Sets the current record's "pr_str1" value
 * @method WacCurrencyRatio setPrStr2()             Sets the current record's "pr_str2" value
 * @method WacCurrencyRatio setFromCurrency()       Sets the current record's "FromCurrency" value
 * @method WacCurrencyRatio setToCurrency()         Sets the current record's "ToCurrency" value
 * 
 * @package    WacERP
 * @subpackage model
 * @author     JianBinBi <jianbinbi@gmail.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseWacCurrencyRatio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wac_currency_ratio');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('ratio', 'float', null, array(
             'type' => 'float',
             'default' => '0',
             'length' => '',
             ));
        $this->hasColumn('pr_int1', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('pr_int2', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'default' => '50',
             'length' => 4,
             ));
        $this->hasColumn('is_avail', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('from_currency_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('to_currency_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pr_str1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pr_str2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WacCurrency as FromCurrency', array(
             'local' => 'from_currency_code',
             'foreign' => 'code'));

        $this->hasOne('WacCurrency as ToCurrency', array(
             'local' => 'to_currency_code',
             'foreign' => 'code'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}