<?php

/**
 * PluginWacMaterialSaleOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialSaleOrderStateTable extends WacOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialSaleOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialSaleOrderState');
    }
}