<?php

/**
 * PluginWacOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacOrderStateHistoryTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacOrderStateHistory');
    }
}