<?php

/**
 * PluginWacMaterialShippingOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialShippingOrderTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialShippingOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialShippingOrder');
    }
}