<?php

/**
 * PluginWacMaterialSalesOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialSalesOrderTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialSalesOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialSalesOrder');
    }
}