<?php

/**
 * PluginWacMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterial');
    }
}