<?php

/**
 * PluginWacMaterialPurchaseOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialPurchaseOrderTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialPurchaseOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialPurchaseOrder');
    }
}