<?php

/**
 * PluginWacStoreroomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacStoreroomTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacStoreroomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacStoreroom');
    }
}