<?php

/**
 * PluginWacSupplierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacSupplierTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacSupplierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacSupplier');
    }
}