<?php

/**
 * PluginWacMaterialSalesOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialSalesOrderItemTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialSalesOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialSalesOrderItem');
    }
}