<?php

/**
 * PluginWacCustomerAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacCustomerAddressTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacCustomerAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacCustomerAddress');
    }
}