<?php

/**
 * PluginWacMaterialPurchaseOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialPurchaseOrderItemTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialPurchaseOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialPurchaseOrderItem');
    }
}