<?php

/**
 * PluginWacOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacOrderStateTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacOrderState');
    }
}