<?php

/**
 * PluginWacMaterialDeliveryOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialDeliveryOrderStateHistoryTable extends WacOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialDeliveryOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialDeliveryOrderStateHistory');
    }
}