<?php

/**
 * PluginWacStorehouseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacStorehouseTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacStorehouseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacStorehouse');
    }
}