<?php

/**
 * PluginWacShippingMethodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacShippingMethodTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacShippingMethodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacShippingMethod');
    }
}