<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WacCustomerAddress', 'wac_db_connection1');

/**
 * BaseWacCustomerAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $customer_id
 * @property string $name
 * @property integer $is_default
 * @property integer $pr_int1
 * @property integer $pr_int2
 * @property string $pr_str1
 * @property string $pr_str2
 * @property integer $priority
 * @property integer $is_avail
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property WacCustomer $Customer
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method integer            getCustomerId()  Returns the current record's "customer_id" value
 * @method string             getName()        Returns the current record's "name" value
 * @method integer            getIsDefault()   Returns the current record's "is_default" value
 * @method integer            getPrInt1()      Returns the current record's "pr_int1" value
 * @method integer            getPrInt2()      Returns the current record's "pr_int2" value
 * @method string             getPrStr1()      Returns the current record's "pr_str1" value
 * @method string             getPrStr2()      Returns the current record's "pr_str2" value
 * @method integer            getPriority()    Returns the current record's "priority" value
 * @method integer            getIsAvail()     Returns the current record's "is_avail" value
 * @method timestamp          getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()   Returns the current record's "updated_at" value
 * @method WacCustomer        getCustomer()    Returns the current record's "Customer" value
 * @method WacCustomerAddress setId()          Sets the current record's "id" value
 * @method WacCustomerAddress setCustomerId()  Sets the current record's "customer_id" value
 * @method WacCustomerAddress setName()        Sets the current record's "name" value
 * @method WacCustomerAddress setIsDefault()   Sets the current record's "is_default" value
 * @method WacCustomerAddress setPrInt1()      Sets the current record's "pr_int1" value
 * @method WacCustomerAddress setPrInt2()      Sets the current record's "pr_int2" value
 * @method WacCustomerAddress setPrStr1()      Sets the current record's "pr_str1" value
 * @method WacCustomerAddress setPrStr2()      Sets the current record's "pr_str2" value
 * @method WacCustomerAddress setPriority()    Sets the current record's "priority" value
 * @method WacCustomerAddress setIsAvail()     Sets the current record's "is_avail" value
 * @method WacCustomerAddress setCreatedAt()   Sets the current record's "created_at" value
 * @method WacCustomerAddress setUpdatedAt()   Sets the current record's "updated_at" value
 * @method WacCustomerAddress setCustomer()    Sets the current record's "Customer" value
 * 
 * @package    WacERP
 * @subpackage model
 * @author     JianBinBi <jianbinbi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWacCustomerAddress extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wac_customer_address');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('customer_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_default', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('pr_int1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pr_int2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pr_str1', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('pr_str2', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '50',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_avail', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WacCustomer as Customer', array(
             'local' => 'customer_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}