<?php

/**
 * sfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    WacStorehouse
 * @subpackage model
 * @author     JianBinBi
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class sfGuardGroup extends PluginsfGuardGroup
{
    public function getPermissionsNames($isArr=false, $separator=',')
    {
        return $this->getPermissionsAttribute("description", $isArr, $separator);
    }

    public function getPermissionsIds($isArr=false, $separator=',')
    {
        return $this->getPermissionsAttribute("id", $isArr, $separator);
    }

    public function getPermissionsAttribute($attribute, $isArr=false, $separator=',')
    {
        $tmpArr = array();
        $groups = $this->getPermissions();
        if($groups->count()>0)
        {
            foreach($groups as $group)
            {
                $method = "get".ucfirst($attribute);
                $tmpArr[] = $group->$method();
            }
        }

        if(!$isArr)
        {
            return implode($separator, $tmpArr);
        }

        return $tmpArr;
    }

}