<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WacMaterialShippingOrder', 'wac_db_connection1');

/**
 * BaseWacMaterialShippingOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property integer $user_id
 * @property integer $src_storehouse_id
 * @property integer $src_storeroom_id
 * @property integer $customer_id
 * @property integer $customer_address_id
 * @property integer $shipping_method_id
 * @property decimal $total_price
 * @property timestamp $biz_date
 * @property integer $pr_int1
 * @property integer $pr_int2
 * @property string $pr_str1
 * @property string $pr_str2
 * @property integer $priority
 * @property integer $is_avail
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer                  getId()                  Returns the current record's "id" value
 * @method string                   getName()                Returns the current record's "name" value
 * @method string                   getCode()                Returns the current record's "code" value
 * @method integer                  getUserId()              Returns the current record's "user_id" value
 * @method integer                  getSrcStorehouseId()     Returns the current record's "src_storehouse_id" value
 * @method integer                  getSrcStoreroomId()      Returns the current record's "src_storeroom_id" value
 * @method integer                  getCustomerId()          Returns the current record's "customer_id" value
 * @method integer                  getCustomerAddressId()   Returns the current record's "customer_address_id" value
 * @method integer                  getShippingMethodId()    Returns the current record's "shipping_method_id" value
 * @method decimal                  getTotalPrice()          Returns the current record's "total_price" value
 * @method timestamp                getBizDate()             Returns the current record's "biz_date" value
 * @method integer                  getPrInt1()              Returns the current record's "pr_int1" value
 * @method integer                  getPrInt2()              Returns the current record's "pr_int2" value
 * @method string                   getPrStr1()              Returns the current record's "pr_str1" value
 * @method string                   getPrStr2()              Returns the current record's "pr_str2" value
 * @method integer                  getPriority()            Returns the current record's "priority" value
 * @method integer                  getIsAvail()             Returns the current record's "is_avail" value
 * @method timestamp                getCreatedAt()           Returns the current record's "created_at" value
 * @method timestamp                getUpdatedAt()           Returns the current record's "updated_at" value
 * @method WacMaterialShippingOrder setId()                  Sets the current record's "id" value
 * @method WacMaterialShippingOrder setName()                Sets the current record's "name" value
 * @method WacMaterialShippingOrder setCode()                Sets the current record's "code" value
 * @method WacMaterialShippingOrder setUserId()              Sets the current record's "user_id" value
 * @method WacMaterialShippingOrder setSrcStorehouseId()     Sets the current record's "src_storehouse_id" value
 * @method WacMaterialShippingOrder setSrcStoreroomId()      Sets the current record's "src_storeroom_id" value
 * @method WacMaterialShippingOrder setCustomerId()          Sets the current record's "customer_id" value
 * @method WacMaterialShippingOrder setCustomerAddressId()   Sets the current record's "customer_address_id" value
 * @method WacMaterialShippingOrder setShippingMethodId()    Sets the current record's "shipping_method_id" value
 * @method WacMaterialShippingOrder setTotalPrice()          Sets the current record's "total_price" value
 * @method WacMaterialShippingOrder setBizDate()             Sets the current record's "biz_date" value
 * @method WacMaterialShippingOrder setPrInt1()              Sets the current record's "pr_int1" value
 * @method WacMaterialShippingOrder setPrInt2()              Sets the current record's "pr_int2" value
 * @method WacMaterialShippingOrder setPrStr1()              Sets the current record's "pr_str1" value
 * @method WacMaterialShippingOrder setPrStr2()              Sets the current record's "pr_str2" value
 * @method WacMaterialShippingOrder setPriority()            Sets the current record's "priority" value
 * @method WacMaterialShippingOrder setIsAvail()             Sets the current record's "is_avail" value
 * @method WacMaterialShippingOrder setCreatedAt()           Sets the current record's "created_at" value
 * @method WacMaterialShippingOrder setUpdatedAt()           Sets the current record's "updated_at" value
 * 
 * @package    WacERP
 * @subpackage model
 * @author     JianBinBi <jianbinbi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWacMaterialShippingOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wac_material_shipping_order');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('src_storehouse_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('src_storeroom_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('customer_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('customer_address_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('shipping_method_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('total_price', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('biz_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pr_int1', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pr_int2', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pr_str1', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('pr_str2', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '50',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_avail', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}