<?php

/**
 * PluginWacMaterialShippingOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialShippingOrderStateHistoryTable extends WacOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialShippingOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialShippingOrderStateHistory');
    }
}