<?php

/**
 * PluginWacMaterialDeliveryOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialDeliveryOrderTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialDeliveryOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialDeliveryOrder');
    }
}