<?php

/**
 * PluginWacMaterialSalesOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialSalesOrderStateTable extends WacOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialSalesOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialSalesOrderState');
    }
}