<?php

/**
 * PluginWacMaterialShippingOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialShippingOrderItemTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialShippingOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialShippingOrderItem');
    }
}