<?php

/**
 * PluginWacMaterialCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialCategoryTable extends WacTreeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialCategory');
    }
}