<?php

/**
 * PluginWacMaterialCategoryLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialCategoryLinkTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialCategoryLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialCategoryLink');
    }
}