<?php

/**
 * PluginWacMaterialPurchaseOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialPurchaseOrderStateHistoryTable extends WacOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialPurchaseOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialPurchaseOrderStateHistory');
    }
}