<?php

/**
 * PluginWacStorehouseMaterialQuantityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacStorehouseMaterialQuantityTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacStorehouseMaterialQuantityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacStorehouseMaterialQuantity');
    }
}