<?php

/**
 * PluginWacMaterialSaleOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialSaleOrderItemTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialSaleOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialSaleOrderItem');
    }
}