<?php

/**
 * PluginWacMaterialShippingOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialShippingOrderStateTable extends WacOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialShippingOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialShippingOrderState');
    }
}