<?php

/**
 * PluginWacMaterialSaleOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialSaleOrderTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialSaleOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialSaleOrder');
    }
}