<?php

/**
 * PluginWacMaterialLangTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialLangTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialLangTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialLang');
    }
}