<?php

/**
 * PluginWacCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacCustomerTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacCustomerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacCustomer');
    }
}