<?php

/**
 * PluginWacStorehouseQuickstatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacStorehouseQuickstatTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacStorehouseQuickstatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacStorehouseQuickstat');
    }
}