<?php

/**
 * PluginWacMaterialSalesOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialSalesOrderStateHistoryTable extends WacOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialSalesOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialSalesOrderStateHistory');
    }
}