<?php

/**
 * PluginWacMaterialPurchaseOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialPurchaseOrderStateTable extends WacOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialPurchaseOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialPurchaseOrderState');
    }
}