<?php

/**
 * PluginWacStorehouseMaterialBizItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacStorehouseMaterialBizItemTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacStorehouseMaterialBizItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacStorehouseMaterialBizItem');
    }
}