<?php

/**
 * PluginWacMaterialDeliveryOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacMaterialDeliveryOrderItemTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacMaterialDeliveryOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacMaterialDeliveryOrderItem');
    }
}