WacProduct:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_product
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    code:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    attribute_set_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    type:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false
  relations:
    Categories:
      class: WacProductCategory
      local: product_id
      foreign: category_id
      refClass: WacProductCategoryLink

WacProductCategory:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_product_category
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    parent_id:
      type: integer(8)
      default: '0'
      notnull: true
    position:
      type: integer(8)
      default: '0'
      notnull: true
    left_number:
      type: integer(8)
      default: '0'
      notnull: true
    right_number:
      type: integer(8)
      default: '0'
      notnull: true
    level:
      type: integer(8)
      default: '0'
      notnull: true
    user_id:
      type: integer(8)
      default: '0'
      notnull: true
    pr_int1:
      type: integer(4)
      default: '0'
    pr_int2:
      type: integer(4)
      default: '0'
    priority:
      type: integer(4)
      default: '50'
    is_avail:
      type: integer(1)
      default: '1'
      notnull: true
    created_at:
      type: timestamp(25)
      notnull: true
    updated_at:
      type: timestamp(25)
      default: '0000-00-00 00:00:00'
      notnull: true
    type: string(255)
    code: string(255)
    name: string(255)
    caption: string(255)
    path: string(255)
    memo: string()
    pr_str1: string(255)
    pr_str2: string(255)
  relations:
    User:
      class: WacGuardUser
      local: user_id
      foreign: id
      type: one
    Parent:
      class: WacProductCategory
      local: parent_id
      foreign: id
      type: one
    Products:
      class: WacProduct
      local: category_id
      foreign: product_id
      refClass: WacProductCategoryLink

WacProductCategoryLink:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_product_cateogry_link
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    product_id:
      type: integer(8)
      primary: true
    category_id:
      type: integer(8)
      primary: true
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false

WacAttributeSet:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_attribute_set
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    code:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false

WacAttribute:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_attribute
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    code:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false

WacAttributeSetAttributeLink:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_attribute_set_attribute_link
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    attribute_set_id:
      type: integer(8)
      primary: true
    attribute_id:
      type: integer(8)
      primary: true
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false

WacProductAttributeNumber:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_product_attribute_number
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    product_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    attribute_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    value:
      type: decimal(10,2)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false

WacProductAttributeText:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_product_attribute_text
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    product_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    attribute_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    value: string()
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false

WacProductAttributeVarchar:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_product_attribute_varchar
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    product_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    attribute_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    value: string(255)
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false

WacProductAttributeObject:
  connection: wac_db_connection1
  package: Storehouse.
  actAs: [Timestampable]
  tableName: wac_product_attribute_object
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    product_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    attribute_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    value:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    pr_int1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_int2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    pr_str1:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pr_str2:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    priority:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    is_avail:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false