<?php

/**
 * PluginWacUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacUnitTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacUnit');
    }
}