<?php

/**
 * PluginWacFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacFileTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacFile');
    }
}