<?php

/**
 * PluginWacLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacLanguageTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacLanguage');
    }
}