<?php

/**
 * PluginWacSystemLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacSystemLogTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacSystemLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacSystemLog');
    }
}