<?php

/**
 * PluginWacSysmsgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacSysmsgTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacSysmsgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacSysmsg');
    }

    /*
     * return value
     */
    public function getContentByCode($cv)
    {
        $resultArr = $this->findOneBy('code', $cv, Doctrine::HYDRATE_ARRAY);
        return nl2br($resultArr['content']);
    }
}