<?php

/**
 * PluginWacUnitTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacUnitTypeTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacUnitTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacUnitType');
    }
}