<?php

/**
 * PluginWacCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacCountryTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacCountry');
    }
}