<?php

/**
 * PluginWacCurrencyRatioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacCurrencyRatioTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacCurrencyRatioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacCurrencyRatio');
    }
}