<?php

/**
 * WacCustomerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacCustomerTable extends PluginWacCustomerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacCustomerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacCustomer');
    }
}