<?php

/**
 * WacMaterialShippingOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialShippingOrderStateHistoryTable extends PluginWacMaterialShippingOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialShippingOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialShippingOrderStateHistory');
    }
}