<?php

/**
 * WacMaterialDeliveryOrderStateHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialDeliveryOrderStateHistoryTable extends PluginWacMaterialDeliveryOrderStateHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialDeliveryOrderStateHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialDeliveryOrderStateHistory');
    }
}