<?php

/**
 * WacMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialTable extends PluginWacMaterialTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterial');
    }
}