<?php

/**
 * WacMaterialSaleOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialSaleOrderStateTable extends PluginWacMaterialSaleOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialSaleOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialSaleOrderState');
    }
}