<?php

/**
 * WacMaterialLangTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialLangTable extends PluginWacMaterialLangTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialLangTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialLang');
    }
}