<?php

/**
 * WacMaterialPurchaseOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialPurchaseOrderTable extends PluginWacMaterialPurchaseOrderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialPurchaseOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialPurchaseOrder');
    }
}