<?php

/**
 * WacMaterialShippingOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialShippingOrderStateTable extends PluginWacMaterialShippingOrderStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialShippingOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialShippingOrderState');
    }
}