<?php

/**
 * WacMaterialCategoryLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialCategoryLinkTable extends PluginWacMaterialCategoryLinkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialCategoryLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialCategoryLink');
    }
}