<?php

/**
 * WacMaterialSaleOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialSaleOrderTable extends PluginWacMaterialSaleOrderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialSaleOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialSaleOrder');
    }
}