<?php

/**
 * WacMaterialDeliveryOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacMaterialDeliveryOrderItemTable extends PluginWacMaterialDeliveryOrderItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacMaterialDeliveryOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacMaterialDeliveryOrderItem');
    }
}