<?php

/**
 * WacStorehouseQuickstatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacStorehouseQuickstatTable extends PluginWacStorehouseQuickstatTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacStorehouseQuickstatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacStorehouseQuickstat');
    }
}