<?php

/**
 * WacStorehouseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacStorehouseTable extends PluginWacStorehouseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacStorehouseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacStorehouse');
    }
}