<?php

/**
 * WacStorehouseMaterialBizItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacStorehouseMaterialBizItemTable extends PluginWacStorehouseMaterialBizItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacStorehouseMaterialBizItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacStorehouseMaterialBizItem');
    }
}