<?php

/**
 * WacStorehouseParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacStorehouseParameterTable extends PluginWacStorehouseParameterTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacStorehouseParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacStorehouseParameter');
    }
}