<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WacUnitRatio', 'wac_db_connection1');

/**
 * BaseWacUnitRatio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $ratio
 * @property integer $pr_int1
 * @property integer $pr_int2
 * @property integer $priority
 * @property integer $is_avail
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property string $from_unit_code
 * @property string $to_unit_code
 * @property string $pr_str1
 * @property string $pr_str2
 * @property WacUnit $FromUnit
 * @property WacUnit $ToUnit
 * 
 * @method integer      getId()             Returns the current record's "id" value
 * @method float        getRatio()          Returns the current record's "ratio" value
 * @method integer      getPrInt1()         Returns the current record's "pr_int1" value
 * @method integer      getPrInt2()         Returns the current record's "pr_int2" value
 * @method integer      getPriority()       Returns the current record's "priority" value
 * @method integer      getIsAvail()        Returns the current record's "is_avail" value
 * @method timestamp    getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp    getUpdatedAt()      Returns the current record's "updated_at" value
 * @method string       getFromUnitCode()   Returns the current record's "from_unit_code" value
 * @method string       getToUnitCode()     Returns the current record's "to_unit_code" value
 * @method string       getPrStr1()         Returns the current record's "pr_str1" value
 * @method string       getPrStr2()         Returns the current record's "pr_str2" value
 * @method WacUnit      getFromUnit()       Returns the current record's "FromUnit" value
 * @method WacUnit      getToUnit()         Returns the current record's "ToUnit" value
 * @method WacUnitRatio setId()             Sets the current record's "id" value
 * @method WacUnitRatio setRatio()          Sets the current record's "ratio" value
 * @method WacUnitRatio setPrInt1()         Sets the current record's "pr_int1" value
 * @method WacUnitRatio setPrInt2()         Sets the current record's "pr_int2" value
 * @method WacUnitRatio setPriority()       Sets the current record's "priority" value
 * @method WacUnitRatio setIsAvail()        Sets the current record's "is_avail" value
 * @method WacUnitRatio setCreatedAt()      Sets the current record's "created_at" value
 * @method WacUnitRatio setUpdatedAt()      Sets the current record's "updated_at" value
 * @method WacUnitRatio setFromUnitCode()   Sets the current record's "from_unit_code" value
 * @method WacUnitRatio setToUnitCode()     Sets the current record's "to_unit_code" value
 * @method WacUnitRatio setPrStr1()         Sets the current record's "pr_str1" value
 * @method WacUnitRatio setPrStr2()         Sets the current record's "pr_str2" value
 * @method WacUnitRatio setFromUnit()       Sets the current record's "FromUnit" value
 * @method WacUnitRatio setToUnit()         Sets the current record's "ToUnit" value
 * 
 * @package    WacERP
 * @subpackage model
 * @author     JianBinBi <jianbinbi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWacUnitRatio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wac_unit_ratio');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('ratio', 'float', null, array(
             'type' => 'float',
             'default' => '0',
             'length' => '',
             ));
        $this->hasColumn('pr_int1', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('pr_int2', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 4,
             ));
        $this->hasColumn('priority', 'integer', 4, array(
             'type' => 'integer',
             'default' => '50',
             'length' => 4,
             ));
        $this->hasColumn('is_avail', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('from_unit_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('to_unit_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pr_str1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('pr_str2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WacUnit as FromUnit', array(
             'local' => 'from_unit_code',
             'foreign' => 'code'));

        $this->hasOne('WacUnit as ToUnit', array(
             'local' => 'to_unit_code',
             'foreign' => 'code'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}