<?php

/**
 * WacCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacCategoryTable extends PluginWacCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacCategory');
    }
}