<?php

/**
 * WacGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacGuardGroupTable extends PluginWacGuardGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacGuardGroup');
    }
}