<?php

/**
 * WacGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WacGuardUserTable extends PluginWacGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WacGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WacGuardUser');
    }
}