<?php

/**
 * PluginWacGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class PluginWacGuardGroup extends BaseWacGuardGroup
{
    public function getPermissionsNames($isArr=false, $separator=',')
    {
        return $this->getPermissionsAttribute("description", $isArr, $separator);
    }

    public function getPermissionsIds($isArr=false, $separator=',')
    {
        return $this->getPermissionsAttribute("id", $isArr, $separator);
    }

    public function getPermissionsAttribute($attribute, $isArr=false, $separator=',')
    {
        $tmpArr = array();
        $groups = $this->getPermissions();
        if($groups->count()>0)
        {
            foreach($groups as $group)
            {
                $method = "get".ucfirst($attribute);
                $tmpArr[] = $group->$method();
            }
        }

        if(!$isArr)
        {
            return implode($separator, $tmpArr);
        }

        return $tmpArr;
    }

}