<?php

/**
 * PluginWacSysmsgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacSysmsgTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacSysmsgTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacSysmsg');
    }
}