<?php

/**
 * PluginWacCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacCategoryTable extends WacTreeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacCategory');
    }

    
}