<?php

/**
 * PluginWacUserParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacUserParameterTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacUserParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacUserParameter');
    }

    /*
     * return value
     */
    public function getOneByCode($code, $isArr=true)
    {
        $conditions = array();
        $conditions['andWhere'][] = "user_id='".sfContext::getInstance()->getUser()->getGuardUser()->getId()."'";
        $conditions['andWhere'][] = "code='{$code}'";

        return $this->getOneByParams($conditions, $isArr);
    }
}