<?php

/**
 * PluginWacWorkflowItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWacWorkflowItemTable extends WacCommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWacWorkflowItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWacWorkflowItem');
    }
}